license="All rights reserved"

modLoader="javafml"

loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="recruits"

version='1.13.5'

displayName="Villager Recruits Mod"
updateJSONURL="https://raw.githubusercontent.com/talhanation/recruits/main/update.json"
displayURL="https://modrinth.com/mod/villager-recruits/versions"

logoFile="logo.png"

credits="talhanation, kaiserroman"
authors="talhanation, kaiserroman"

# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod adds hire-able Villager Recruits with different Ranks like in M&B-Bannerlord into Minecraft.
'''

